import Banner from "../src/components/Banner/Banner";
import Head from "next/head";
import { Inter } from "@next/font/google";
import { useQuery, gql } from "@apollo/client";
import {
  GET_ALL_POSTS,
  GET_ALL_PRODUCTS,
  GET_HOME_PAGE,
} from "../src/graphql/queries";
// Components
import Navbar from "../src/components/Navbar/Navbar";
import NewProducts from "../src/components/NewProducts/NewProducts";
import Footer from "../src/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const {
    loading: postLoading,
    error: postError,
    data: post,
  } = useQuery(GET_ALL_POSTS);
  const {
    loading: productsLoading,
    error: productsError,
    data: products,
  } = useQuery(GET_ALL_PRODUCTS);
  const {
    loading: homePageLoading,
    error: homePageError,
    data: homePage,
  } = useQuery(GET_HOME_PAGE);

  if (postLoading || productsLoading || homePageLoading)
    return <p>Loading...</p>;
  if (postError || productsError || homePageError) return <p>Error : Error</p>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <Navbar></Navbar>
        <Banner data={homePage.startpage} />
        <NewProducts {...products} />
        <Footer />
      </div>
    </>
  );
}
