import Banner from "../src/components/Banner/Banner";
import Head from "next/head";
import { useQuery } from "@apollo/client";
import { GET_ALL_PRODUCTS, GET_HOME_PAGE } from "../src/graphql/queries";
import Navbar from "../src/components/Navbar/Navbar";
import NewProducts from "../src/components/NewProducts/NewProducts";
import Footer from "../src/components/Footer/Footer";
import { StructuredText } from "react-datocms";

export default function Home() {
  const {
    loading: productsLoading,
    error: productsError,
    data: products,
  } = useQuery(GET_ALL_PRODUCTS);
  const {
    loading: homePageLoading,
    error: homePageError,
    data: homePage,
  } = useQuery(GET_HOME_PAGE);

  if (productsLoading || homePageLoading) return <p>Loading...</p>;
  if (productsError || homePageError) return <p>Error : Error</p>;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <Navbar></Navbar>
        <Banner {...homePage.startpage} />
        <NewProducts {...products} />
        <StructuredText data={homePage.startpage.content.value} />
        <Footer />
      </div>
    </>
  );
}
